name: update Readme Puzzle Stats
on:
  # schedule:
  #   - cron:  '30 0 * 12 *'
  workflow_dispatch:
  push:

jobs:
  updateReadmeStats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
          cache: false
      - name: build aoc2022
        run: |
          CGO_ENABLED=0 go build -o aoc2022 .
      - name: update Puzzle Stats
        run: |
          rep=0
          tmpfile="$(mktemp)"
          while read line; do
            if [ "_$line" == '_<!-- ci:result:end -->' ] ; then
              rep=0
              echo '```' >> "$tmpfile"
              AOC_REPEATS=50 AOC_USE_CACHED_RESULT=true ./aoc2022 >> "$tmpfile"
              echo '```' >> "$tmpfile"
            fi
            [ $rep -eq 1 ] && continue
            [ "_$line" == '_<!-- ci:result:start -->' ] && rep=1
            echo "$line" >> "$tmpfile"
          done < README.md
          mv "$tmpfile" README.md
      - name: git add
        run: |
          git add */.cache.json
          git add README.md
      - name: setup git
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "Github Bot"
      - name: git commit
        run: |
          files_changed=$(git diff --name-only --cached | wc -l)
          if [ $files_changed -eq 0 ] ; then
            exit 0
          else
            git commit -m "Update Puzzle Stats"
          fi
      - name: git push
        run: |
          git pull --rebase https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git


